module.exports = [
    {
        id: 1,
        name: "Catan",
        category: "Dice",
        count_min: 3,
        count_max: 4,
        age_min: 10,
        playtime: 68,
        description: "The women and men of your expedition build the first two settlements. Fortunately, the land is rich in natural resources. You build roads and new settlements that eventually become cities. Will you succeed in gaining supremacy on Catan?",
        price_weekly: 9.99,
        available_until: "2022-09-23",
        user_email: "moinuddin8510@gmail.com",
    },
    {
        id: 2,
        name: "Dominion",
        category: "Card Game",
        count_min: 2,
        count_max: 4,
        age_min: 13,
        playtime: 30,
        description: "You are a monarch, like your parents before you, a ruler of a small pleasant kingdom of rivers and evergreens. Unlike your parents, however, you have hopes and dreams! You want a bigger and more pleasant kingdom, you want a Dominion!",
        price_weekly: 7.5,
        available_until: "2022-09-16",
        user_email: "moinuddin8510@gmail.com",
    },
    {
        id: 3,
        name: "Exploding Kittens",
        category: "Animals",
        count_min: 2,
        count_max: 5,
        age_min: 7,
        playtime: 15,
        description: "Exploding Kittens is a card game for people who are into kittens and explosions and laser beams and sometimes goats.",
        price_weekly: 5,
        available_until: "2022-09-20",
        user_email: "moinuddin8510@gmail.com",
    },
    {
        id: 4,
        name: "Monopoly",
        category: "Economic",
        count_min: 2,
        count_max: 8,
        age_min: 8,
        playtime: 170,
        description: "The thrill of bankrupting an opponent, the possibility of playing a 9 hour game, and the absolution between winning and losing, could change with the roll of the dice.",
        price_weekly: 100,
        available_until: "2022-12-31",
        user_email: "test@test.com",
    },
];