module.exports = [
    {
        id: 1,
        name: "Catan",
        category: "Dice",
        count_min: 3,
        count_max: 4,
        age_min: 10,
        playtime: 68,
        description:
            "The women and men of your expedition build the first two settlements. Fortunately, the land is rich in natural resources. You build roads and new settlements that eventually become cities. Will you succeed in gaining supremacy on Catan? Barter trade dominates the scene. Some resources you have in abundance, other resources are scarce. Ore for wool, brick for lumber - you trade according to what is needed for your current building projects. Proceed strategically! If you found your settlements in the right places and skillfully trade your resources, then the odds will be in your favor. But your opponents are smart too. \n To begin the game, we build the game board using hexagonal terrain tiles. Catan is born - a beautiful island with mountains, pastures, hills, fields, and forests, surrounded by the sea. \n Each of us places two small houses on spaces where three terrain hexes meet. They are our starting settlements. \n And so it begins. I roll two dice. An “11”! Each terrain hex is marked with a die roll number. Each player who owns a settlement adjacent to a terrain hex marked with the number rolled receives a resource produced by this hex. Hills produce brick, forests produce lumber, mountains produce ore, fields produce grain, and pastures produce wool. \n We use these resources to expand across Catan: we build roads and new settlements, or we upgrade our existing settlements to cities. For example, a road costs 1 brick and 1 lumber. If we do not have the necessary resources, we can acquire them by trading with our opponents. \n Each settlement is worth 1 victory point and each city is worth 2 victory points. If you expand cleverly, you may be the first player to reach 10 victory points and thus win the game!",
        price_weekly: 9.99,
        available_until: "2022-10-18",
        user_email: "moinuddin8510@gmail.com",
    },
    {
        id: 2,
        name: "Dominion",
        category: "Card Game",
        count_min: 2,
        count_max: 4,
        age_min: 13,
        playtime: 30,
        description:
            'You are a monarch, like your parents before you, a ruler of a small pleasant kingdom of rivers and evergreens. Unlike your parents, however, you have hopes and dreams! You want a bigger and more pleasant kingdom, with more rivers and a wider variety of trees. You want a Dominion!   In all directions lie fiefs, freeholds, and feodums. All are small bits of land, controlled by petty lords and verging on anarchy. You will bring civilization to these people, uniting them under your banner. \n In   Dominion  , each player starts with an identical, very small deck of cards. In the center of the table is a selection of other cards the players can "buy" as they can afford them. Through their selection of cards to buy, and how they play their hands as they draw them, the players construct their deck on the fly, striving for the most efficient path to the precious victory points by game end.',
        price_weekly: 9.99,
        available_until: "2022-10-20",
        user_email: "moinuddin8510@gmail.com",
    },
    {
        id: 3,
        name: "Exploding Kittens",
        category: "Animals",
        count_min: 2,
        count_max: 5,
        age_min: 7,
        playtime: 15,
        description:
            "Exploding Kittens  is a card game for people who are into kittens and explosions and laser beams and sometimes goats. \n In this highly-strategic, kitty-powered version of Russian roulette, players draw cards until someone draws an exploding kitten, at which point they explode, they are Dead, and they are out of the game -- unless that player has a defuse card, which can defuse the kitten using things like laser pointers, belly rubs, and catnip sandwiches. All of the other cards in the deck are used to move, mitigate, or avoid the exploding kittens.",
        price_weekly: 5.99,
        available_until: "2022-10-26",
        user_email: "moinuddin8510@gmail.com",
    },
    {
        id: 4,
        name: "Uno",
        category: "Card Game",
        count_min: 2,
        count_max: 10,
        age_min: 7,
        playtime: 30,
        description:
            "Now the classic card game of matching colors and numbers comes with customizable Wild Cards for added excitement! Players take turns racing to get rid of all their cards by matching a card in their hand with the current card shown on top of the deck either by color or number. Special Action cards deliver game-changing moments and help defeat opponents! Use the Swap Hands card to change hands with any other opponent and write your own rules using the 3 customizable (and erasable) Wild Cards! \n If you can't make a match, you must draw from the central pile! Don't forget to shout \"UNO\" when you only have one card remaining! The first player to reach 500 points wins. \n Includes 112 cards and instructions. You'll find 19 of each color (red, green, blue, and yellow), plus 8 Draw Two, Reverse and Skip cards in every color, along with 4 Wild Cards, 4 Wild Draw Four cards, 1 Wild Swap Hands Card and 3 Wild Customizable cards.",
        price_weekly: 4.99,
        available_until: "2022-10-19",
        user_email: "moinuddin8510@gmail.com",
    },
    {
        id: 5,
        name: "chess",
        category: "Abstract",
        count_min: 2,
        count_max: 2,
        age_min: 6,
        playtime: 75,
        description:
            "Chess  is a game for two players on an 8x8 grid with alternating light and dark spaces. Each player has a matching set of 16 pieces, including 8 pawns, 2 rooks, 2 knights, 2 bishops, a queen, and a king. Each type of piece has its own rules for movement. The object of the game is to capture the opponent's king.",
        price_weekly: 7.99,
        available_until: "2022-10-07",
        user_email: "moinuddin8510@gmail.com",
    },
    {
        id: 6,
        name: "Jenga",
        category: "Dexterity",
        count_min: 1,
        count_max: 8,
        age_min: 6,
        playtime: 20,
        description:
            "The suspense is building — and so are you! Carefully pull a wood block out of the tower and place it on top. It’s easy at first, but as more blocks get pulled, the tower starts to get unsteady…and you’ll be on the edge of your seat just trying to keep it from falling! Stay cool, stay calm and stay steady, because the last player to complete their turn before someone makes it topple, wins!",
        price_weekly: 4.99,
        available_until: "2022-10-12",
        user_email: "moinuddin8510@gmail.com",
    },
    {
        id: 7,
        name: "Sushi Go!",
        category: "Card Game",
        count_min: 2,
        count_max: 5,
        age_min: 8,
        playtime: 23,
        description:
            "In this fast-playing card game, the goal is to grab the best combination of sushi dishes as they whiz by. Score points for making the most maki rolls or for collecting a full set of sashimi. Dip your favorite nigiri in wasabi to triple its value! But be sure to leave room for dessert or else you'll eat into your score! Gather the most points and consider yourself the sushi master! \n  Sushi Go!  takes the card-drafting mechanism of  Fairy Tale  and  7 Wonders  and distills it into a twenty-minute game that anyone can play. The dynamics of \"draft and pass\" are brought to the fore, while keeping the rules to a minimum. As you see the first few hands of cards, you must quickly assess the make-up of the round and decide which type of sushi you'll go for. Then, each turn you'll need to weigh which cards to keep and which to pass on. The different scoring combinations allow for some clever plays and nasty blocks. Round to round, you must also keep your eye on the goal of having the most pudding cards at the end of the game!",
        price_weekly: 5.99,
        available_until: "2022-10-29",
        user_email: "moinuddin8510@gmail.com",
    },
    {
        id: 8,
        name: "Splendor",
        category: "Card Game",
        count_min: 2,
        count_max: 4,
        age_min: 10,
        playtime: 45,
        description:
            "As a wealthy Renaissance merchant, acquire mines and transportation, hire artisans and woo the nobility. Create the most fantastic jewelry to become the best-known merchant of them all! Acquire precious stones to trade them for development cards. Use development cards to acquire more gem stones. Use your gems and gold to create the most fantastic jewelry, and appeal to the nobles to gain the prestige you need to win.  Splendor is a fast-paced and addictive game of chip-collecting and card development. Players are merchants of the Renaissance trying to buy gem mines, means of transportation, shops; all in order to acquire the most prestige points. If you're wealthy enough, you might even receive a visit from a noble at some point, which of course will further increase your prestige.  On your turn, you may (1) collect chips (gems), or (2) buy and build a card, or (3) reserve one card. If you collect chips, you take either three different kinds of chips or two chips of the same kind. If you buy a card, you pay its price in chips and add it to your playing area. To reserve a card, you place it in front of you face down for later building; this costs you a round, but you also get gold in the form of a joker chip, which you can use as any gem.  All of the cards you buy increase your wealth as they give you a permanent gem bonus for later buys; some of the cards also give you prestige points. In order to win the game, you must reach 15 prestige points before your opponents do.",
        price_weekly: 8.99,
        available_until: "2022-10-07",
        user_email: "moinuddin8510@gmail.com",
    },
    {
        id: 9,
        name: "Scrabble",
        category: "Word Game",
        count_min: 2,
        count_max: 4,
        age_min: 10,
        playtime: 90,
        description:
            "The classic word-on-word showdown. Use your letters to score points and challenge your family and friends. A double or triple letter or word space will let you earn big points. It’s your word against theirs!",
        price_weekly: 6.99,
        available_until: "2022-10-20",
        user_email: "moinuddin8510@gmail.com",
    },
    {
        id: 10,
        name: "Operation",
        category: "Children's Game",
        count_min: 1,
        count_max: 6,
        age_min: 6,
        playtime: 10,
        description:
            "In the Operation game, kids get to be the doctor and make Cavity Sam better or get the buzzer! Perform successful action noted on the cards by picking funny ailment pieces out of the game tray with a pair of tweezers. But watch out! If the tweezers touch the sides of the openings, the buzzer goes off and Cavity Sam's nose lights up! Then players look for their Specialist card that fits that action to earn an even higher fee. The player with the most money after all of the Funatomy parts have been removed wins the game! Hasbro Gaming and all related terms are trademarks of Hasbro.",
        price_weekly: 5.99,
        available_until: "2022-10-21",
        user_email: "moinuddin8510@gmail.com",
    },
    {
        id: 11,
        name: "Dominion",
        category: "Card Game",
        count_min: 2,
        count_max: 4,
        age_min: 13,
        playtime: 30,
        description:
            'You are a monarch, like your parents before you, a ruler of a small pleasant kingdom of rivers and evergreens. Unlike your parents, however, you have hopes and dreams! You want a bigger and more pleasant kingdom, with more rivers and a wider variety of trees. You want a Dominion!   In all directions lie fiefs, freeholds, and feodums. All are small bits of land, controlled by petty lords and verging on anarchy. You will bring civilization to these people, uniting them under your banner. \n In   Dominion  , each player starts with an identical, very small deck of cards. In the center of the table is a selection of other cards the players can "buy" as they can afford them. Through their selection of cards to buy, and how they play their hands as they draw them, the players construct their deck on the fly, striving for the most efficient path to the precious victory points by game end.',
        price_weekly: 10.0,
        available_until: "2022-10-31",
        user_email: "jerryj@hotmail.com",
    },
    {
        id: 12,
        name: "Dixit",
        category: "Abstract",
        count_min: 3,
        count_max: 6,
        age_min: 8,
        playtime: 36,
        description:
            'Each player is the storyteller in turn. The storyteller chooses a card from their hand and gives a clue (word, phrase, song...). The other players choose the card in their hand that best fits this clue. The Storyteller’s card is shuffled with the players’ cards, then all the chosen cards are revealed. Which is the storyteller’s card? Players secretly vote, then the scoring begins! \n How to Play: \n 1. On your turn, as the storyteller, choose a card from your hand and give a clue for it (word, sentence, song, etc.). \n 2. All other players choose one of their cards that best fits your clue. Shuffle and reveal all chosen cards. \n 3. All players then secretly guess which card is yours, using the voting tokens. Once all votes are done, the scoring begins! \n  Winner of the 2010 "Spiel des Jahres" German Board Game of the Year Award.  \n  Contents:  84 Oversized Image Cards 1 Scoreboard 6 Wooden Rabbits 36 Voting Tokens Rules',
        price_weekly: 10.0,
        available_until: "2022-10-31",
        user_email: "jerryj@hotmail.com",
    },
    {
        id: 13,
        name: "Jenga",
        category: "Dexterity",
        count_min: 1,
        count_max: 8,
        age_min: 6,
        playtime: 20,
        description:
            "The suspense is building — and so are you! Carefully pull a wood block out of the tower and place it on top. It’s easy at first, but as more blocks get pulled, the tower starts to get unsteady…and you’ll be on the edge of your seat just trying to keep it from falling! Stay cool, stay calm and stay steady, because the last player to complete their turn before someone makes it topple, wins!",
        price_weekly: 10.0,
        available_until: "2022-10-31",
        user_email: "jerryj@hotmail.com",
    },
    {
        id: 14,
        name: "Sushi Go!",
        category: "Card Game",
        count_min: 2,
        count_max: 5,
        age_min: 8,
        playtime: 23,
        description:
            "In this fast-playing card game, the goal is to grab the best combination of sushi dishes as they whiz by. Score points for making the most maki rolls or for collecting a full set of sashimi. Dip your favorite nigiri in wasabi to triple its value! But be sure to leave room for dessert or else you'll eat into your score! Gather the most points and consider yourself the sushi master! \n  Sushi Go!  takes the card-drafting mechanism of  Fairy Tale  and  7 Wonders  and distills it into a twenty-minute game that anyone can play. The dynamics of \"draft and pass\" are brought to the fore, while keeping the rules to a minimum. As you see the first few hands of cards, you must quickly assess the make-up of the round and decide which type of sushi you'll go for. Then, each turn you'll need to weigh which cards to keep and which to pass on. The different scoring combinations allow for some clever plays and nasty blocks. Round to round, you must also keep your eye on the goal of having the most pudding cards at the end of the game!",
        price_weekly: 10.0,
        available_until: "2022-10-31",
        user_email: "jerryj@hotmail.com",
    },
    {
        id: 15,
        name: "Connect 4",
        category: "Abstract",
        count_min: 2,
        count_max: 2,
        age_min: 6,
        playtime: 10,
        description:
            "Drop your red or yellow discs in the grid and be the first to get 4 in a row to win. If your opponent is getting too close to 4 in a row, block them with your own disc. Whoever wins can pull out the slider bar to release all the discs and start the fun all over again.",
        price_weekly: 10.0,
        available_until: "2022-10-31",
        user_email: "jerryj@hotmail.com",
    },
    {
        id: 16,
        name: "Scrabble",
        category: "Word Game",
        count_min: 2,
        count_max: 4,
        age_min: 10,
        playtime: 90,
        description:
            "The classic word-on-word showdown. Use your letters to score points and challenge your family and friends. A double or triple letter or word space will let you earn big points. It’s your word against theirs!",
        price_weekly: 10.0,
        available_until: "2022-10-31",
        user_email: "jerryj@hotmail.com",
    },
    {
        id: 17,
        name: "Pandemic",
        category: "Medical",
        count_min: 2,
        count_max: 4,
        age_min: 8,
        playtime: 53,
        description:
            "After five years of Pandemic, hundreds of thousands of players have contracted the virus! To celebrate this milestone, Pandemic has been completely re-designed. With new artwork by Chris Quilliams (Clash of Cultures, Merchants & Marauders), Pandemic will now have a more modern look, inside and outside the box. With two new characters (the Contingency Planner and the Quarantine Specialist) face the game in ways you never thought possible as brand-new, virulent challenges await you! \n In   Pandemic  , several virulent diseases have broken out simultaneously all over the world! The players are disease-fighting specialists whose mission is to treat disease hotspots while researching cures for each of four plagues before they get out of hand. \n The game board depicts several major population centers on Earth. On each turn, a player can use up to four actions to travel between cities, treat infected populaces, discover a cure, or build a research station. A deck of cards provides the players with these abilities, but sprinkled throughout this deck are  Epidemic!  cards that accelerate and intensify the diseases' activity. A second, separate deck of cards controls the \"normal\" spread of the infections. \n Taking a unique role within the team, players must plan their strategy to mesh with their specialists' strengths in order to conquer the diseases. For example, the Operations Expert can build research stations which are needed to find cures for the diseases and which allow for greater mobility between cities; the Scientist needs only four cards of a particular disease to cure it instead of the normal five—but the diseases are spreading quickly and time is running out. If one or more diseases spreads beyond recovery or if too much time elapses, the players all lose. If they cure the four diseases, they all win! \n The 2013 edition of  Pandemic  includes two new characters—the Contingency Planner and the Quarantine Specialist—not available in earlier editions of the game. \n Artists: \n Joshua Cappel (graphics and illustration) \n Régis Moulun (cover painting) \n Chris Quilliams (2013 edition)",
        price_weekly: 10.0,
        available_until: "2022-10-31",
        user_email: "jerryj@hotmail.com",
    },
    {
        id: 18,
        name: "Uno",
        category: "Card Game",
        count_min: 2,
        count_max: 10,
        age_min: 7,
        playtime: 30,
        description:
            "Now the classic card game of matching colors and numbers comes with customizable Wild Cards for added excitement! Players take turns racing to get rid of all their cards by matching a card in their hand with the current card shown on top of the deck either by color or number. Special Action cards deliver game-changing moments and help defeat opponents! Use the Swap Hands card to change hands with any other opponent and write your own rules using the 3 customizable (and erasable) Wild Cards! \n If you can't make a match, you must draw from the central pile! Don't forget to shout \"UNO\" when you only have one card remaining! The first player to reach 500 points wins. \n Includes 112 cards and instructions. You'll find 19 of each color (red, green, blue, and yellow), plus 8 Draw Two, Reverse and Skip cards in every color, along with 4 Wild Cards, 4 Wild Draw Four cards, 1 Wild Swap Hands Card and 3 Wild Customizable cards.",
        price_weekly: 2.5,
        available_until: "2022-11-16",
        user_email: "barbar123@yahoo.ca",
    },
    {
        id: 19,
        name: "Sushi Go!",
        category: "Card Game",
        count_min: 2,
        count_max: 5,
        age_min: 8,
        playtime: 23,
        description:
            "In this fast-playing card game, the goal is to grab the best combination of sushi dishes as they whiz by. Score points for making the most maki rolls or for collecting a full set of sashimi. Dip your favorite nigiri in wasabi to triple its value! But be sure to leave room for dessert or else you'll eat into your score! Gather the most points and consider yourself the sushi master! \n  Sushi Go!  takes the card-drafting mechanism of  Fairy Tale  and  7 Wonders  and distills it into a twenty-minute game that anyone can play. The dynamics of \"draft and pass\" are brought to the fore, while keeping the rules to a minimum. As you see the first few hands of cards, you must quickly assess the make-up of the round and decide which type of sushi you'll go for. Then, each turn you'll need to weigh which cards to keep and which to pass on. The different scoring combinations allow for some clever plays and nasty blocks. Round to round, you must also keep your eye on the goal of having the most pudding cards at the end of the game!",
        price_weekly: 4.5,
        available_until: "2022-11-05",
        user_email: "barbar123@yahoo.ca",
    },
    {
        id: 20,
        name: "Splendor",
        category: "Card Game",
        count_min: 2,
        count_max: 4,
        age_min: 10,
        playtime: 45,
        description:
            "As a wealthy Renaissance merchant, acquire mines and transportation, hire artisans and woo the nobility. Create the most fantastic jewelry to become the best-known merchant of them all! Acquire precious stones to trade them for development cards. Use development cards to acquire more gem stones. Use your gems and gold to create the most fantastic jewelry, and appeal to the nobles to gain the prestige you need to win.  Splendor is a fast-paced and addictive game of chip-collecting and card development. Players are merchants of the Renaissance trying to buy gem mines, means of transportation, shops; all in order to acquire the most prestige points. If you're wealthy enough, you might even receive a visit from a noble at some point, which of course will further increase your prestige.  On your turn, you may (1) collect chips (gems), or (2) buy and build a card, or (3) reserve one card. If you collect chips, you take either three different kinds of chips or two chips of the same kind. If you buy a card, you pay its price in chips and add it to your playing area. To reserve a card, you place it in front of you face down for later building; this costs you a round, but you also get gold in the form of a joker chip, which you can use as any gem.  All of the cards you buy increase your wealth as they give you a permanent gem bonus for later buys; some of the cards also give you prestige points. In order to win the game, you must reach 15 prestige points before your opponents do.",
        price_weekly: 7.5,
        available_until: "2022-11-17",
        user_email: "barbar123@yahoo.ca",
    },
    {
        id: 21,
        name: "Checkers",
        category: "Abstract",
        count_min: 2,
        count_max: 2,
        age_min: 6,
        playtime: 30,
        description:
            "The classic game of red versus black. On a square checkered board, where individual color squares alternate between the two colors, the two sides are divided with each player controlling half. Discs of each players' color are placed in the very back two rows of their side, with single spaces in between. \n The goal of the game is to move forward and hop over your opponent's pieces to eliminate them before they do the same. Pieces can only move on space towards their opponent's side and only to an adjacent, diagonal location. The only exception to this is when you attack, or \"jump\", your opponent. This move has you moving two spaces toward your opponent's side in a diagonal direction where one of your opponent's discs is located in between. If you are successful, the jumped piece is removed from the board. You may not make a move if there is a piece blocking your end location (your's right next to you for regular moves, or two in a row in the case of an attack jump. You are only ever allowed to make legal moves that have a location to go to. Blocked pieces cannot move. \n In addition to moving the one direction toward your opponent's side, trying to attack (jump) your opponent's pieces. , there is an additional bonus move. If you are able to move one of your discs all the way to the far edge of your opponent's side, your piece is turned into a \"king\" with an additional checker disc added on top of it to signify this. The bonus of a king is they are able to move both forward AND BACKWARD as long as they adhere to all other movement rules. \n Once all of a player's checker discs (player pieces) are removed from the board because they have been jumped, that player loses and the other player is victorious.",
        price_weekly: 4.5,
        available_until: "2022-11-17",
        user_email: "barbar123@yahoo.ca",
    },
    {
        id: 22,
        name: "Catan",
        category: "Dice",
        count_min: 3,
        count_max: 4,
        age_min: 10,
        playtime: 68,
        description:
            "The women and men of your expedition build the first two settlements. Fortunately, the land is rich in natural resources. You build roads and new settlements that eventually become cities. Will you succeed in gaining supremacy on Catan? Barter trade dominates the scene. Some resources you have in abundance, other resources are scarce. Ore for wool, brick for lumber - you trade according to what is needed for your current building projects. Proceed strategically! If you found your settlements in the right places and skillfully trade your resources, then the odds will be in your favor. But your opponents are smart too. \n To begin the game, we build the game board using hexagonal terrain tiles. Catan is born - a beautiful island with mountains, pastures, hills, fields, and forests, surrounded by the sea. \n Each of us places two small houses on spaces where three terrain hexes meet. They are our starting settlements. \n And so it begins. I roll two dice. An “11”! Each terrain hex is marked with a die roll number. Each player who owns a settlement adjacent to a terrain hex marked with the number rolled receives a resource produced by this hex. Hills produce brick, forests produce lumber, mountains produce ore, fields produce grain, and pastures produce wool. \n We use these resources to expand across Catan: we build roads and new settlements, or we upgrade our existing settlements to cities. For example, a road costs 1 brick and 1 lumber. If we do not have the necessary resources, we can acquire them by trading with our opponents. \n Each settlement is worth 1 victory point and each city is worth 2 victory points. If you expand cleverly, you may be the first player to reach 10 victory points and thus win the game!",
        price_weekly: 8.0,
        available_until: "2022-10-28",
        user_email: "darko6@gmail.com",
    },
    {
        id: 23,
        name: "Risk",
        category: "Territory Building",
        count_min: 2,
        count_max: 6,
        age_min: 10,
        playtime: 120,
        description:
            "Welcome to the world of  Risk . It’s exciting. It’s unpredictable. It’s all about battling your way to global domination, one territory at a time. And it’s easy to get into the game, fast! \n In Risk, you focus on your strategy. You decide on your tactical scheme. You figure out where to place your troops, and who and where you will attack and how often. Every move is a risk that will bring either victory or defeat. Go for the win! \n  60th Anniversary Edition:  \n Betrayal. Alliances. Surprise attacks. Risk continues to be one of the world's most popular and influential strategic board games decades after its inception. The special 60th Anniversary Edition of Risk celebrates its legacy with premium packaging and game pieces. For true Risk fans, the included game guide reveals the history of Risk. It also features 5 ways to play, including the classic game plus the original 1957  La conquete du monde  rules. \n Anything goes on the battlefield of the risk game. Using strategy, smarts, and a little bit of luck, a player will either defeat the enemy or be defeated. Take over the world in this game of strategy conquest!",
        price_weekly: 7.0,
        available_until: "2022-10-28",
        user_email: "darko6@gmail.com",
    },
    {
        id: 24,
        name: "pandemic",
        category: "Medical",
        count_min: 2,
        count_max: 4,
        age_min: 8,
        playtime: 53,
        description:
            "After five years of Pandemic, hundreds of thousands of players have contracted the virus! To celebrate this milestone, Pandemic has been completely re-designed. With new artwork by Chris Quilliams (Clash of Cultures, Merchants & Marauders), Pandemic will now have a more modern look, inside and outside the box. With two new characters (the Contingency Planner and the Quarantine Specialist) face the game in ways you never thought possible as brand-new, virulent challenges await you! \n In   Pandemic  , several virulent diseases have broken out simultaneously all over the world! The players are disease-fighting specialists whose mission is to treat disease hotspots while researching cures for each of four plagues before they get out of hand. \n The game board depicts several major population centers on Earth. On each turn, a player can use up to four actions to travel between cities, treat infected populaces, discover a cure, or build a research station. A deck of cards provides the players with these abilities, but sprinkled throughout this deck are  Epidemic!  cards that accelerate and intensify the diseases' activity. A second, separate deck of cards controls the \"normal\" spread of the infections. \n Taking a unique role within the team, players must plan their strategy to mesh with their specialists' strengths in order to conquer the diseases. For example, the Operations Expert can build research stations which are needed to find cures for the diseases and which allow for greater mobility between cities; the Scientist needs only four cards of a particular disease to cure it instead of the normal five—but the diseases are spreading quickly and time is running out. If one or more diseases spreads beyond recovery or if too much time elapses, the players all lose. If they cure the four diseases, they all win! \n The 2013 edition of  Pandemic  includes two new characters—the Contingency Planner and the Quarantine Specialist—not available in earlier editions of the game. \n Artists: \n Joshua Cappel (graphics and illustration) \n Régis Moulun (cover painting) \n Chris Quilliams (2013 edition)",
        price_weekly: 9.0,
        available_until: "2022-10-28",
        user_email: "darko6@gmail.com",
    },
    {
        id: 25,
        name: "Dixit",
        category: "Abstract",
        count_min: 3,
        count_max: 6,
        age_min: 8,
        playtime: 36,
        description:
            'Each player is the storyteller in turn. The storyteller chooses a card from their hand and gives a clue (word, phrase, song...). The other players choose the card in their hand that best fits this clue. The Storyteller’s card is shuffled with the players’ cards, then all the chosen cards are revealed. Which is the storyteller’s card? Players secretly vote, then the scoring begins! \n How to Play: \n 1. On your turn, as the storyteller, choose a card from your hand and give a clue for it (word, sentence, song, etc.). \n 2. All other players choose one of their cards that best fits your clue. Shuffle and reveal all chosen cards. \n 3. All players then secretly guess which card is yours, using the voting tokens. Once all votes are done, the scoring begins! \n  Winner of the 2010 "Spiel des Jahres" German Board Game of the Year Award.  \n  Contents:  84 Oversized Image Cards 1 Scoreboard 6 Wooden Rabbits 36 Voting Tokens Rules',
        price_weekly: 8.88,
        available_until: "2022-10-19",
        user_email: "figkai@outlook.com",
    },
    {
        id: 26,
        name: "Chess",
        category: "Abstract",
        count_min: 2,
        count_max: 2,
        age_min: 6,
        playtime: 75,
        description:
            "Chess  is a game for two players on an 8x8 grid with alternating light and dark spaces. Each player has a matching set of 16 pieces, including 8 pawns, 2 rooks, 2 knights, 2 bishops, a queen, and a king. Each type of piece has its own rules for movement. The object of the game is to capture the opponent's king.",
        price_weekly: 6.75,
        available_until: "2022-10-20",
        user_email: "figkai@outlook.com",
    },
    {
        id: 27,
        name: "Splendor",
        category: "Card Game",
        count_min: 2,
        count_max: 4,
        age_min: 10,
        playtime: 45,
        description:
            "As a wealthy Renaissance merchant, acquire mines and transportation, hire artisans and woo the nobility. Create the most fantastic jewelry to become the best-known merchant of them all! Acquire precious stones to trade them for development cards. Use development cards to acquire more gem stones. Use your gems and gold to create the most fantastic jewelry, and appeal to the nobles to gain the prestige you need to win.  Splendor is a fast-paced and addictive game of chip-collecting and card development. Players are merchants of the Renaissance trying to buy gem mines, means of transportation, shops; all in order to acquire the most prestige points. If you're wealthy enough, you might even receive a visit from a noble at some point, which of course will further increase your prestige.  On your turn, you may (1) collect chips (gems), or (2) buy and build a card, or (3) reserve one card. If you collect chips, you take either three different kinds of chips or two chips of the same kind. If you buy a card, you pay its price in chips and add it to your playing area. To reserve a card, you place it in front of you face down for later building; this costs you a round, but you also get gold in the form of a joker chip, which you can use as any gem.  All of the cards you buy increase your wealth as they give you a permanent gem bonus for later buys; some of the cards also give you prestige points. In order to win the game, you must reach 15 prestige points before your opponents do.",
        price_weekly: 7.77,
        available_until: "2022-10-17",
        user_email: "figkai@outlook.com",
    },
    {
        id: 28,
        name: "Catan",
        category: "Dice",
        count_min: 3,
        count_max: 4,
        age_min: 10,
        playtime: 68,
        description:
            "The women and men of your expedition build the first two settlements. Fortunately, the land is rich in natural resources. You build roads and new settlements that eventually become cities. Will you succeed in gaining supremacy on Catan? Barter trade dominates the scene. Some resources you have in abundance, other resources are scarce. Ore for wool, brick for lumber - you trade according to what is needed for your current building projects. Proceed strategically! If you found your settlements in the right places and skillfully trade your resources, then the odds will be in your favor. But your opponents are smart too. \n To begin the game, we build the game board using hexagonal terrain tiles. Catan is born - a beautiful island with mountains, pastures, hills, fields, and forests, surrounded by the sea. \n Each of us places two small houses on spaces where three terrain hexes meet. They are our starting settlements. \n And so it begins. I roll two dice. An “11”! Each terrain hex is marked with a die roll number. Each player who owns a settlement adjacent to a terrain hex marked with the number rolled receives a resource produced by this hex. Hills produce brick, forests produce lumber, mountains produce ore, fields produce grain, and pastures produce wool. \n We use these resources to expand across Catan: we build roads and new settlements, or we upgrade our existing settlements to cities. For example, a road costs 1 brick and 1 lumber. If we do not have the necessary resources, we can acquire them by trading with our opponents. \n Each settlement is worth 1 victory point and each city is worth 2 victory points. If you expand cleverly, you may be the first player to reach 10 victory points and thus win the game!",
        price_weekly: 10.25,
        available_until: "2022-10-23",
        user_email: "hhharmony@gmail.com",
    },
    {
        id: 29,
        name: "Exploding Kittens",
        category: "Animals",
        count_min: 2,
        count_max: 5,
        age_min: 7,
        playtime: 15,
        description:
            "Exploding Kittens  is a card game for people who are into kittens and explosions and laser beams and sometimes goats. \n In this highly-strategic, kitty-powered version of Russian roulette, players draw cards until someone draws an exploding kitten, at which point they explode, they are Dead, and they are out of the game -- unless that player has a defuse card, which can defuse the kitten using things like laser pointers, belly rubs, and catnip sandwiches. All of the other cards in the deck are used to move, mitigate, or avoid the exploding kittens.",
        price_weekly: 7.25,
        available_until: "2022-10-30",
        user_email: "hhharmony@gmail.com",
    },
    {
        id: 30,
        name: "Dixit",
        category: "Abstract",
        count_min: 3,
        count_max: 6,
        age_min: 8,
        playtime: 36,
        description:
            'Each player is the storyteller in turn. The storyteller chooses a card from their hand and gives a clue (word, phrase, song...). The other players choose the card in their hand that best fits this clue. The Storyteller’s card is shuffled with the players’ cards, then all the chosen cards are revealed. Which is the storyteller’s card? Players secretly vote, then the scoring begins! \n How to Play: \n 1. On your turn, as the storyteller, choose a card from your hand and give a clue for it (word, sentence, song, etc.). \n 2. All other players choose one of their cards that best fits your clue. Shuffle and reveal all chosen cards. \n 3. All players then secretly guess which card is yours, using the voting tokens. Once all votes are done, the scoring begins! \n  Winner of the 2010 "Spiel des Jahres" German Board Game of the Year Award.  \n  Contents:  84 Oversized Image Cards 1 Scoreboard 6 Wooden Rabbits 36 Voting Tokens Rules',
        price_weekly: 8.75,
        available_until: "2022-10-23",
        user_email: "hhharmony@gmail.com",
    },
    {
        id: 31,
        name: "Risk",
        category: "Territory Building",
        count_min: 2,
        count_max: 6,
        age_min: 10,
        playtime: 120,
        description:
            "Welcome to the world of  Risk . It’s exciting. It’s unpredictable. It’s all about battling your way to global domination, one territory at a time. And it’s easy to get into the game, fast! \n In Risk, you focus on your strategy. You decide on your tactical scheme. You figure out where to place your troops, and who and where you will attack and how often. Every move is a risk that will bring either victory or defeat. Go for the win! \n  60th Anniversary Edition:  \n Betrayal. Alliances. Surprise attacks. Risk continues to be one of the world's most popular and influential strategic board games decades after its inception. The special 60th Anniversary Edition of Risk celebrates its legacy with premium packaging and game pieces. For true Risk fans, the included game guide reveals the history of Risk. It also features 5 ways to play, including the classic game plus the original 1957  La conquete du monde  rules. \n Anything goes on the battlefield of the risk game. Using strategy, smarts, and a little bit of luck, a player will either defeat the enemy or be defeated. Take over the world in this game of strategy conquest!",
        price_weekly: 7.75,
        available_until: "2022-10-16",
        user_email: "hhharmony@gmail.com",
    },
    {
        id: 32,
        name: "Connect 4",
        category: "Abstract",
        count_min: 2,
        count_max: 2,
        age_min: 6,
        playtime: 10,
        description:
            "Drop your red or yellow discs in the grid and be the first to get 4 in a row to win. If your opponent is getting too close to 4 in a row, block them with your own disc. Whoever wins can pull out the slider bar to release all the discs and start the fun all over again.",
        price_weekly: 8.25,
        available_until: "2022-10-23",
        user_email: "hhharmony@gmail.com",
    },
    {
        id: 33,
        name: "Scrabble",
        category: "Word Game",
        count_min: 2,
        count_max: 4,
        age_min: 10,
        playtime: 90,
        description:
            "The classic word-on-word showdown. Use your letters to score points and challenge your family and friends. A double or triple letter or word space will let you earn big points. It’s your word against theirs!",
        price_weekly: 6.75,
        available_until: "2022-10-30",
        user_email: "hhharmony@gmail.com",
    },
    {
        id: 34,
        name: "pandemic",
        category: "Medical",
        count_min: 2,
        count_max: 4,
        age_min: 8,
        playtime: 53,
        description:
            "After five years of Pandemic, hundreds of thousands of players have contracted the virus! To celebrate this milestone, Pandemic has been completely re-designed. With new artwork by Chris Quilliams (Clash of Cultures, Merchants & Marauders), Pandemic will now have a more modern look, inside and outside the box. With two new characters (the Contingency Planner and the Quarantine Specialist) face the game in ways you never thought possible as brand-new, virulent challenges await you! \n In   Pandemic  , several virulent diseases have broken out simultaneously all over the world! The players are disease-fighting specialists whose mission is to treat disease hotspots while researching cures for each of four plagues before they get out of hand. \n The game board depicts several major population centers on Earth. On each turn, a player can use up to four actions to travel between cities, treat infected populaces, discover a cure, or build a research station. A deck of cards provides the players with these abilities, but sprinkled throughout this deck are  Epidemic!  cards that accelerate and intensify the diseases' activity. A second, separate deck of cards controls the \"normal\" spread of the infections. \n Taking a unique role within the team, players must plan their strategy to mesh with their specialists' strengths in order to conquer the diseases. For example, the Operations Expert can build research stations which are needed to find cures for the diseases and which allow for greater mobility between cities; the Scientist needs only four cards of a particular disease to cure it instead of the normal five—but the diseases are spreading quickly and time is running out. If one or more diseases spreads beyond recovery or if too much time elapses, the players all lose. If they cure the four diseases, they all win! \n The 2013 edition of  Pandemic  includes two new characters—the Contingency Planner and the Quarantine Specialist—not available in earlier editions of the game. \n Artists: \n Joshua Cappel (graphics and illustration) \n Régis Moulun (cover painting) \n Chris Quilliams (2013 edition)",
        price_weekly: 9.75,
        available_until: "2022-10-09",
        user_email: "hhharmony@gmail.com",
    },
    {
        id: 35,
        name: "Catan",
        category: "Dice",
        count_min: 3,
        count_max: 4,
        age_min: 10,
        playtime: 68,
        description:
            "The women and men of your expedition build the first two settlements. Fortunately, the land is rich in natural resources. You build roads and new settlements that eventually become cities. Will you succeed in gaining supremacy on Catan? Barter trade dominates the scene. Some resources you have in abundance, other resources are scarce. Ore for wool, brick for lumber - you trade according to what is needed for your current building projects. Proceed strategically! If you found your settlements in the right places and skillfully trade your resources, then the odds will be in your favor. But your opponents are smart too. \n To begin the game, we build the game board using hexagonal terrain tiles. Catan is born - a beautiful island with mountains, pastures, hills, fields, and forests, surrounded by the sea. \n Each of us places two small houses on spaces where three terrain hexes meet. They are our starting settlements. \n And so it begins. I roll two dice. An “11”! Each terrain hex is marked with a die roll number. Each player who owns a settlement adjacent to a terrain hex marked with the number rolled receives a resource produced by this hex. Hills produce brick, forests produce lumber, mountains produce ore, fields produce grain, and pastures produce wool. \n We use these resources to expand across Catan: we build roads and new settlements, or we upgrade our existing settlements to cities. For example, a road costs 1 brick and 1 lumber. If we do not have the necessary resources, we can acquire them by trading with our opponents. \n Each settlement is worth 1 victory point and each city is worth 2 victory points. If you expand cleverly, you may be the first player to reach 10 victory points and thus win the game!",
        price_weekly: 10.0,
        available_until: "2022-10-26",
        user_email: "lamblarson@gmail.com",
    },
    {
        id: 36,
        name: "Dixit",
        category: "Abstract",
        count_min: 3,
        count_max: 6,
        age_min: 8,
        playtime: 36,
        description:
            'Each player is the storyteller in turn. The storyteller chooses a card from their hand and gives a clue (word, phrase, song...). The other players choose the card in their hand that best fits this clue. The Storyteller’s card is shuffled with the players’ cards, then all the chosen cards are revealed. Which is the storyteller’s card? Players secretly vote, then the scoring begins! \n How to Play: \n 1. On your turn, as the storyteller, choose a card from your hand and give a clue for it (word, sentence, song, etc.). \n 2. All other players choose one of their cards that best fits your clue. Shuffle and reveal all chosen cards. \n 3. All players then secretly guess which card is yours, using the voting tokens. Once all votes are done, the scoring begins! \n  Winner of the 2010 "Spiel des Jahres" German Board Game of the Year Award.  \n  Contents:  84 Oversized Image Cards 1 Scoreboard 6 Wooden Rabbits 36 Voting Tokens Rules',
        price_weekly: 5.0,
        available_until: "2022-11-02",
        user_email: "lamblarson@gmail.com",
    },
    {
        id: 37,
        name: "Sushi Go!",
        category: "Card Game",
        count_min: 2,
        count_max: 5,
        age_min: 8,
        playtime: 23,
        description:
            "In this fast-playing card game, the goal is to grab the best combination of sushi dishes as they whiz by. Score points for making the most maki rolls or for collecting a full set of sashimi. Dip your favorite nigiri in wasabi to triple its value! But be sure to leave room for dessert or else you'll eat into your score! Gather the most points and consider yourself the sushi master! \n  Sushi Go!  takes the card-drafting mechanism of  Fairy Tale  and  7 Wonders  and distills it into a twenty-minute game that anyone can play. The dynamics of \"draft and pass\" are brought to the fore, while keeping the rules to a minimum. As you see the first few hands of cards, you must quickly assess the make-up of the round and decide which type of sushi you'll go for. Then, each turn you'll need to weigh which cards to keep and which to pass on. The different scoring combinations allow for some clever plays and nasty blocks. Round to round, you must also keep your eye on the goal of having the most pudding cards at the end of the game!",
        price_weekly: 6.0,
        available_until: "2022-11-02",
        user_email: "lamblarson@gmail.com",
    },
    {
        id: 38,
        name: "Connect 4",
        category: "Abstract",
        count_min: 2,
        count_max: 2,
        age_min: 6,
        playtime: 10,
        description:
            "Drop your red or yellow discs in the grid and be the first to get 4 in a row to win. If your opponent is getting too close to 4 in a row, block them with your own disc. Whoever wins can pull out the slider bar to release all the discs and start the fun all over again.",
        price_weekly: 5.0,
        available_until: "2022-10-26",
        user_email: "lamblarson@gmail.com",
    },
    {
        id: 39,
        name: "Scrabble",
        category: "Word Game",
        count_min: 2,
        count_max: 4,
        age_min: 10,
        playtime: 90,
        description:
            "The classic word-on-word showdown. Use your letters to score points and challenge your family and friends. A double or triple letter or word space will let you earn big points. It’s your word against theirs!",
        price_weekly: 6.0,
        available_until: "2022-10-19",
        user_email: "lamblarson@gmail.com",
    },
    {
        id: 40,
        name: "Pandemic",
        category: "Medical",
        count_min: 2,
        count_max: 4,
        age_min: 8,
        playtime: 53,
        description:
            "After five years of Pandemic, hundreds of thousands of players have contracted the virus! To celebrate this milestone, Pandemic has been completely re-designed. With new artwork by Chris Quilliams (Clash of Cultures, Merchants & Marauders), Pandemic will now have a more modern look, inside and outside the box. With two new characters (the Contingency Planner and the Quarantine Specialist) face the game in ways you never thought possible as brand-new, virulent challenges await you! \n In   Pandemic  , several virulent diseases have broken out simultaneously all over the world! The players are disease-fighting specialists whose mission is to treat disease hotspots while researching cures for each of four plagues before they get out of hand. \n The game board depicts several major population centers on Earth. On each turn, a player can use up to four actions to travel between cities, treat infected populaces, discover a cure, or build a research station. A deck of cards provides the players with these abilities, but sprinkled throughout this deck are  Epidemic!  cards that accelerate and intensify the diseases' activity. A second, separate deck of cards controls the \"normal\" spread of the infections. \n Taking a unique role within the team, players must plan their strategy to mesh with their specialists' strengths in order to conquer the diseases. For example, the Operations Expert can build research stations which are needed to find cures for the diseases and which allow for greater mobility between cities; the Scientist needs only four cards of a particular disease to cure it instead of the normal five—but the diseases are spreading quickly and time is running out. If one or more diseases spreads beyond recovery or if too much time elapses, the players all lose. If they cure the four diseases, they all win! \n The 2013 edition of  Pandemic  includes two new characters—the Contingency Planner and the Quarantine Specialist—not available in earlier editions of the game. \n Artists: \n Joshua Cappel (graphics and illustration) \n Régis Moulun (cover painting) \n Chris Quilliams (2013 edition)",
        price_weekly: 10.0,
        available_until: "2022-10-12",
        user_email: "lamblarson@gmail.com",
    },
    {
        id: 41,
        name: "Dominion",
        category: "Card Game",
        count_min: 2,
        count_max: 4,
        age_min: 13,
        playtime: 30,
        description:
            'You are a monarch, like your parents before you, a ruler of a small pleasant kingdom of rivers and evergreens. Unlike your parents, however, you have hopes and dreams! You want a bigger and more pleasant kingdom, with more rivers and a wider variety of trees. You want a Dominion!   In all directions lie fiefs, freeholds, and feodums. All are small bits of land, controlled by petty lords and verging on anarchy. You will bring civilization to these people, uniting them under your banner. \n In   Dominion  , each player starts with an identical, very small deck of cards. In the center of the table is a selection of other cards the players can "buy" as they can afford them. Through their selection of cards to buy, and how they play their hands as they draw them, the players construct their deck on the fly, striving for the most efficient path to the precious victory points by game end.',
        price_weekly: 12.12,
        available_until: "2022-11-30",
        user_email: "noraneare64@yahoo.com",
    },
    {
        id: 42,
        name: "Uno",
        category: "Card Game",
        count_min: 2,
        count_max: 10,
        age_min: 7,
        playtime: 30,
        description:
            "Now the classic card game of matching colors and numbers comes with customizable Wild Cards for added excitement! Players take turns racing to get rid of all their cards by matching a card in their hand with the current card shown on top of the deck either by color or number. Special Action cards deliver game-changing moments and help defeat opponents! Use the Swap Hands card to change hands with any other opponent and write your own rules using the 3 customizable (and erasable) Wild Cards! \n If you can't make a match, you must draw from the central pile! Don't forget to shout \"UNO\" when you only have one card remaining! The first player to reach 500 points wins. \n Includes 112 cards and instructions. You'll find 19 of each color (red, green, blue, and yellow), plus 8 Draw Two, Reverse and Skip cards in every color, along with 4 Wild Cards, 4 Wild Draw Four cards, 1 Wild Swap Hands Card and 3 Wild Customizable cards.",
        price_weekly: 7.07,
        available_until: "2022-11-30",
        user_email: "noraneare64@yahoo.com",
    },
    {
        id: 43,
        name: "Chess",
        category: "Abstract",
        count_min: 2,
        count_max: 2,
        age_min: 6,
        playtime: 75,
        description:
            "Chess  is a game for two players on an 8x8 grid with alternating light and dark spaces. Each player has a matching set of 16 pieces, including 8 pawns, 2 rooks, 2 knights, 2 bishops, a queen, and a king. Each type of piece has its own rules for movement. The object of the game is to capture the opponent's king.",
        price_weekly: 11.11,
        available_until: "2022-10-29",
        user_email: "noraneare64@yahoo.com",
    },
    {
        id: 44,
        name: "Catan",
        category: "Dice",
        count_min: 3,
        count_max: 4,
        age_min: 10,
        playtime: 68,
        description:
            "The women and men of your expedition build the first two settlements. Fortunately, the land is rich in natural resources. You build roads and new settlements that eventually become cities. Will you succeed in gaining supremacy on Catan? Barter trade dominates the scene. Some resources you have in abundance, other resources are scarce. Ore for wool, brick for lumber - you trade according to what is needed for your current building projects. Proceed strategically! If you found your settlements in the right places and skillfully trade your resources, then the odds will be in your favor. But your opponents are smart too. \n To begin the game, we build the game board using hexagonal terrain tiles. Catan is born - a beautiful island with mountains, pastures, hills, fields, and forests, surrounded by the sea. \n Each of us places two small houses on spaces where three terrain hexes meet. They are our starting settlements. \n And so it begins. I roll two dice. An “11”! Each terrain hex is marked with a die roll number. Each player who owns a settlement adjacent to a terrain hex marked with the number rolled receives a resource produced by this hex. Hills produce brick, forests produce lumber, mountains produce ore, fields produce grain, and pastures produce wool. \n We use these resources to expand across Catan: we build roads and new settlements, or we upgrade our existing settlements to cities. For example, a road costs 1 brick and 1 lumber. If we do not have the necessary resources, we can acquire them by trading with our opponents. \n Each settlement is worth 1 victory point and each city is worth 2 victory points. If you expand cleverly, you may be the first player to reach 10 victory points and thus win the game!",
        price_weekly: 10.0,
        available_until: "2022-10-20",
        user_email: "pollypolly1@gmail.com",
    },
    {
        id: 45,
        name: "monopoly",
        category: "Economic",
        count_min: 2,
        count_max: 8,
        age_min: 8,
        playtime: 170,
        description:
            "The thrill of bankrupting an opponent, the possibility of playing a 9 hour game, and the absolution between winning and losing, could change with the roll of the dice. Experience the ups and downs by collecting property color’s sets to build houses, and hopefully upgrading to a hotel. But don’t play just for certain colors, or else your opponent may change their strategy. \n The more properties each player owns, the more rent can be charged, but trading is where the game can help you, or hurt you. So, be wise! \n Chance cards could be worth money, like $10 for winning second place in a beauty pageant or sending you to “Go” for an extra $200; but you might just get the one that says, “Go To Jail”. \n Buy, Sell, Dream and Scheme to Win it All! \n Turn a debt into an ultimate victory!",
        price_weekly: 15.5,
        available_until: "2022-11-10",
        user_email: "richie@rocketmail.com",
    },
    {
        id: 46,
        name: "Connect 4",
        category: "Abstract",
        count_min: 2,
        count_max: 2,
        age_min: 6,
        playtime: 10,
        description:
            "Drop your red or yellow discs in the grid and be the first to get 4 in a row to win. If your opponent is getting too close to 4 in a row, block them with your own disc. Whoever wins can pull out the slider bar to release all the discs and start the fun all over again.",
        price_weekly: 5.0,
        available_until: "2022-10-07",
        user_email: "zzillow101@yahoo.ca",
    },
    {
        id: 47,
        name: "MONOPOLY",
        category: "Economic",
        count_min: 2,
        count_max: 8,
        age_min: 8,
        playtime: 170,
        description:
            "The thrill of bankrupting an opponent, the possibility of playing a 9 hour game, and the absolution between winning and losing, could change with the roll of the dice. Experience the ups and downs by collecting property color’s sets to build houses, and hopefully upgrading to a hotel. But don’t play just for certain colors, or else your opponent may change their strategy. \n The more properties each player owns, the more rent can be charged, but trading is where the game can help you, or hurt you. So, be wise! \n Chance cards could be worth money, like $10 for winning second place in a beauty pageant or sending you to “Go” for an extra $200; but you might just get the one that says, “Go To Jail”. \n Buy, Sell, Dream and Scheme to Win it All! \n Turn a debt into an ultimate victory!",
        price_weekly: 7.67,
        available_until: "2022-10-07",
        user_email: "zzillow101@yahoo.ca",
    },
    {
        id: 48,
        name: "codenames",
        category: "Card Game",
        count_min: 2,
        count_max: 8,
        age_min: 10,
        playtime: 15,
        description:
            "The two rival spymasters know the secret identities of 25 agents. Their teammates know the agents only by their CODENAMES.  The teams compete to see who can make contact with all of their agents first. Spymasters give one-word clues that can point to multiple words on the board. Their teammates try to guess words of the right color while avoiding those that belong to the opposing team. And everyone wants to avoid the assassin.  Codenames: win or lose, it's fun to figure out the clues.",
        price_weekly: 2.0,
        available_until: "2022-12-31",
        user_email: "nekhilnagi@aws.com",
    },
];
